### ISSUE TITLE
[DOCS ISSUE] Page: Lotus: import data from IPFS

### ISSUE THREAD

**Issue by jick68** [filecoin-project/filecoin-docs#907] opened 2021-06-17 12:04 UTC
This MOP is incomplete.

After enabling ipfs and initializing IPFS daemon, pinning data in ipfs, and waiting for data transfer to complete in ipfs, I then attempt to make a deal and receive the following error:

ERROR: failed to start deal: computing commP failed: generating CommP: blockstore: block not found

This error does not occur when I create a file manually via vim editor, add the file via lotus client import, and then work to make the deal.

What is the step to import IPFS data into lotus after it has been pinned in ipfs daemon on same machine?

**Comment by jick68** [comment] 2021-06-17 13:37
Add steps to ensure that user knows they must use --config flag to point lotus to config file

```bash 
lotus daemon stop
lotus daemon --config=~/.lotus/config.toml
```

**Comment by jick68** [comment] 2021-06-17 13:37
tks filecoin team! really appreciate everyone's work here!

**Comment by johnnymatthews** [comment] 2021-08-06 12:39
Duplicate of #906. See the [Filecoin Discussion for support](https://github.com/filecoin-project/lotus/discussions)

**Closed by johnnymatthews** 2021-08-06 12:39 UTC
Labels: need/triage
