### ISSUE TITLE
Reorganize docs navigation

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-docs#1253] opened 2022-05-10 17:29 UTC
This is a placeholder issue for reorganizing the Filecoin Docs, and orienting it more around helping users _make technical design decisions_ before jumping straight to command line.

Based on a [cardsort exercise](https://miro.com/app/board/uXjVOIHCAqc=/) by @johnnymatthews @mishmosh @TkKonstantin, here are the 6 planned high-level sections. Work for each section will be tracked in a separate issue.

1. Overview - to come
1. Storage - to come
1. Developers - addressed in https://github.com/filecoin-project/filecoin-docs/pull/1484
1. Storage Providers - to come
1. Protocol - to come
1. About - to come

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/1306020/167687400-e4f03261-2616-40a8-8fa0-6fe1efbc290c.png">

**Comment by jenks-guo-filecoin** [comment] 2022-05-18 06:13
I love the persona based approach.

**Comment by mishmosh** [comment] 2022-09-30 20:00
Quick update: This was initially planned well before FVM launch, so no surprise that it's not well-represented here.

However, I think there’s a pretty straightforward path to making sure FVM content is highly visible & discoverable. **Build** is being renamed to **Developers** (#1410), and we can have a 2nd-level section there for FVM. So it would look like:
- Developers
  - Overview (#1368, live)
  - Storage (or Storage Helpers) (#1370, live)
  - FVM (new!)
  - Protocol Layer (#1407, in review)

**Comment by johnnymatthews** [comment] 2022-10-04 14:12
I'd like to put FVM in it's own top-level section, if we can. We only have 4 levels of navigation (by design):

1. Topbar nav.
1. Sidebar nav dropdown.
1. Sidebar nav item/link.
1. Table of contents.

![screen](https://user-images.githubusercontent.com/9611008/193841742-db9b9dd9-5f3c-4a85-9f24-0da545beaec8.png)

With this structure, we can have:

- Topbar: **FVM**
- Sidebar nav dropdowns: **Concepts**, **How tos**, **Examples**, **Reference**.

This structure gives us lots of flexibility to create good pages and articles for FVM.

**Comment by johnnymatthews** [comment] 2022-12-26 21:59
Developers section addresses in https://github.com/filecoin-project/filecoin-docs/pull/1484.

**Comment by johnnymatthews** [comment] 2023-02-27 19:40
Closing in favour of https://github.com/filecoin-project/filecoin-docs/issues/1692

**Closed by johnnymatthews** 2023-02-27 19:40 UTC
Labels: dif/hard, effort/days, P1
